# Makefile for Linux samples code

obj-$(CONFIG_SAMPLES)	+= kobject/ kprobes/ trace_events/ livepatch/ \
			   hw_breakpoint/ kfifo/ kdb/ hidraw/ rpmsg/ seccomp/ \
			   configfs/
			   https://www.pscp.tv/w/1YqKDpeeQnkKV
			   https://www.pscp.tv/w/1YqKDpeeQnkKV
